name: html_imports
dependencies:
  initialize: any
  web_components:
    path: '../../'
dev_dependencies:
  test: '^0.12.0'
transformers:
- web_components:
    $include: '**/*_test.html'
    entry_points: test/basic_test.html
