name: browser
version: 0.10.0+3
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/browser
description: >-
  DEPRECATED package providing support for rewriting script tags
  to change a Dart file reference to the corresponding Javascript in
  browsers that don't support Dart.
environment:
  sdk: ">=1.8.0 <2.0.0"
